const images = {
  home_start: require('./home_start.png'),
  //A유형
  userA1: require('./illust/TypeA/7A-1.png'),
  userA2: require('./illust/TypeA/7A-2.png'),
  userA3: require('./illust/TypeA/7A-3.png'),
  userA4: require('./illust/TypeA/7A-4.png'),
  userA5: require('./illust/TypeA/7A-5.png'),
  userA1R: require('./illust/TypeA/A1R.png'),
  userA2R: require('./illust/TypeA/A2R.png'),
  userA3R: require('./illust/TypeA/A3R.png'),
  userA4R: require('./illust/TypeA/A4R.png'),
  userA5R: require('./illust/TypeA/A5R.png'),
  //B유형
  userB1: require('./illust/TypeB/8B-1.png'),
  userB2: require('./illust/TypeB/8B-2.png'),
  userB3: require('./illust/TypeB/8B-3.png'),
  userB4: require('./illust/TypeB/8B-4.png'),
  userB5: require('./illust/TypeB/8B-5.png'),
  userB1R: require('./illust/TypeB/B1R.png'),
  userB2R: require('./illust/TypeB/B2R.png'),
  userB3R: require('./illust/TypeB/B3R.png'),
  userB4R: require('./illust/TypeB/B4R.png'),
  userB5R: require('./illust/TypeB/B5R.png'),
  //C유형
  userC1: require('./illust/TypeC/8C-1.png'),
  userC2: require('./illust/TypeC/8C-2.png'),
  userC3: require('./illust/TypeC/8C-3.png'),
  userC4: require('./illust/TypeC/8C-4.png'),
  userC5: require('./illust/TypeC/8C-5.png'),
  userC1R: require('./illust/TypeC/C1R.png'),
  userC2R: require('./illust/TypeC/C2R.png'),
  userC3R: require('./illust/TypeC/C3R.png'),
  userC4R: require('./illust/TypeC/C4R.png'),
  userC5R: require('./illust/TypeC/C5R.png'),
  //D유형
  userD1: require('./illust/TypeD/8D-1.png'),
  userD2: require('./illust/TypeD/8D-2.png'),
  userD3: require('./illust/TypeD/8D-3.png'),
  userD4: require('./illust/TypeD/8D-4.png'),
  userD5: require('./illust/TypeD/8D-5.png'),
  userD1R: require('./illust/TypeD/D1R.png'),
  userD2R: require('./illust/TypeD/D2R.png'),
  userD3R: require('./illust/TypeD/D3R.png'),
  userD4R: require('./illust/TypeD/D4R.png'),
  userD5R: require('./illust/TypeD/D5R.png'),
  //E유형
  userE1: require('./illust/TypeE/7E-1.png'),
  userE2: require('./illust/TypeE/7E-2.png'),
  userE3: require('./illust/TypeE/7E-3.png'),
  userE4: require('./illust/TypeE/7E-4.png'),
  userE5: require('./illust/TypeE/7E-5.png'),
  userE1R: require('./illust/TypeE/E1R.png'),
  userE2R: require('./illust/TypeE/E2R.png'),
  userE3R: require('./illust/TypeE/E3R.png'),
  userE4R: require('./illust/TypeE/E4R.png'),
  userE5R: require('./illust/TypeE/E5R.png'),

  null: null,
};
export default images;
